USE [master]
GO

/****** Object:  Database [StockManagementSystemDb]    Script Date: 31/07/2018 02:07:26 ******/
CREATE DATABASE [StockManagementSystemDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StockManagementSystemDb', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\StockManagementSystemDb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'StockManagementSystemDb_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\StockManagementSystemDb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [StockManagementSystemDb] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockManagementSystemDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StockManagementSystemDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [StockManagementSystemDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StockManagementSystemDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StockManagementSystemDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StockManagementSystemDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StockManagementSystemDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StockManagementSystemDb] SET  MULTI_USER 
GO

ALTER DATABASE [StockManagementSystemDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StockManagementSystemDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StockManagementSystemDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StockManagementSystemDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [StockManagementSystemDb] SET  READ_WRITE 
GO

